(function(_ds){var window=this;var sW=function(a,b){_ds.cn(a,"transform","translate3d("+b+"px,0px,0px)")};var vW=function(a){a.o=tW(a,".devsite-top-logo-row-wrapper-wrapper");a.j=tW(a,".devsite-collapsible-section");a.ea=tW(a,".devsite-doc-set-nav-row");a.setAttribute("top-row--height",`${a.o}`);a.setAttribute("bottom-row--height",`${a.j}`);a.setAttribute("bottom-tabs--height",`${a.ea}`);a.style.setProperty("--devsite-js-top-row--height",`${a.o}px`);a.style.setProperty("--devsite-js-bottom-row--height",`${a.j}px`);a.style.setProperty("--devsite-js-bottom-tabs--height",`${a.ea}px`);uW(a);a.m.resolve()},
uW=function(a){const b=a.querySelector(".devsite-collapsible-section");a.offset>=a.j&&!a.hasAttribute("bottom-row--hidden")?a.setAttribute("bottom-row--hidden",""):a.offset<a.j-a.ea&&a.hasAttribute("bottom-row--hidden")&&a.removeAttribute("bottom-row--hidden");b&&a.offset!==a.Aa&&(_ds.cn(b,"transform",`translate3d(0, -${a.offset}px, 0)`),wW(a),a.Aa=a.offset);document.body.style.setProperty("--devsite-js-header-height",`${a.qa()}px`)},aIa=function(a){var b=a.querySelector(".devsite-top-logo-row-middle");
const c=a.querySelector("devsite-search"),d=a.querySelector(".devsite-search-background");if(b&&c&&d){a.xa.removeAll();a.ua&&window.cancelAnimationFrame(a.ua);c.removeAttribute("transition");a.removeAttribute("search-expanded");var e=new _ds.hk(b.offsetWidth,b.offsetHeight);b=new _ds.hk(c.offsetWidth,c.offsetHeight);var f=_ds.yn(c,"margin"),g=document.documentElement.getAttribute("dir")==="rtl"?1:-1,h=(e.width-f.left-f.right)/b.width;e=(e.width-(b.width+f.left+f.right))*g;var k=(f=a.hasAttribute("search-active"))?
e:0,l=f?h:1;_ds.cn(d,{opacity:1,width:`${b.width}px`,height:`${b.height}px`});sW(c,a.hasAttribute("search-active")?0:e);a.xa.Kb(d,_ds.fl,()=>{const m=a.querySelector("devsite-search"),n=a.querySelector(".devsite-search-background");n&&(n.style.opacity="0");m&&(m.removeAttribute("transition"),sW(m,0),a.hasAttribute("search-active")?a.setAttribute("search-expanded",""):a.removeAttribute("search-expanded"))});a.ua=window.requestAnimationFrame(()=>{c.setAttribute("transition","");_ds.cn(d,"transform",
"scale3d("+l+",1,1)");sW(c,k)})}},bIa=async function(a,b){if(a.hasAttribute("billboard")){var c=a.querySelector("devsite-search"),d=a.querySelector("devsite-search input.devsite-search-query");a=a.querySelector(".devsite-header-billboard-search devsite-search");var e=a==null?void 0:a.querySelector("input.devsite-search-query");c&&d&&a&&e&&(b?(c.removeAttribute("disabled"),document.activeElement===e&&(await _ds.Ml(),d.focus()),a.setAttribute("disabled","")):(a.removeAttribute("disabled"),document.activeElement===
d&&e.focus(),c.setAttribute("disabled","")))}},cIa=function(a){a.eventHandler.listen(a,"devsite-search-toggle",b=>{b=b.getBrowserEvent();_ds.cl(b.target,null,"devsite-top-logo-row-middle")&&(b.detail.active?a.setAttribute("search-active",""):a.removeAttribute("search-active"))});a.eventHandler.listen(document.body,"devsite-sitemask-hidden",()=>{document.body.removeAttribute("devsite-book-nav--open")});a.eventHandler.listen(window,"resize",()=>{xW(a)});a.eventHandler.listen(document.body,["devsite-page-loaded",
"devsite-content-updated"],()=>{xW(a)});a.eventHandler.listen(a,"click",b=>{b.defaultPrevented||b.target.getAttribute("id")!=="devsite-hamburger-menu"||(b.preventDefault(),b.stopPropagation(),document.body.setAttribute("devsite-book-nav--open",""),a.dispatchEvent(new CustomEvent("devsite-sitemask-show",{bubbles:!0})))})},yW=function(a){if(!a.querySelector(".devsite-search-background")&&(a=a.querySelector(".devsite-top-logo-row-middle"))){const b=document.createElement("div");b.classList.add("devsite-search-background");
b.style.opacity="1";a.appendChild(b)}},wW=function(a){a.j===0?a.setAttribute("no-lower-row",""):a.removeAttribute("no-lower-row");a.querySelector(".devsite-header-billboard")?a.setAttribute("billboard",""):a.removeAttribute("billboard")},xW=function(a){window.requestAnimationFrame(()=>{a.ya.fb()})},tW=function(a,b){return(a=a.querySelector(b))?a.getBoundingClientRect().height:0},zW=function(a,b){for(var c=0;c<b.attributes.length;++c){var d=b.attributes.item(c);a.hasAttribute(d.name)||b.removeAttribute(d.name)}for(c=
0;c<a.attributes.length;++c)d=a.attributes.item(c),b.setAttribute(d.name,d.value)},AW=function(a,b,c){b=b.querySelector(c);c=a.querySelector(c);b&&c&&(a.updated=!0,_ds.Uj(a,c,b))},dIa=function(a,b){const c=a.querySelectorAll(".devsite-header-link");b=b.querySelectorAll(".devsite-header-link");const d=a.querySelector("devsite-language-selector");a=a.querySelector("devsite-user");for(const e of b)d?d.after(e):a&&a.before(e);c.forEach(e=>{e.remove()})},eIa=class extends _ds.Vj{constructor(){super(...arguments);
this.eventHandler=new _ds.D;this.Aa=-1;this.xa=new _ds.D;this.ua=0;this.ra=new MutationObserver(()=>{vW(this)});this.ya=new _ds.Og(()=>{vW(this);wW(this)},15);this.authUser=void 0;this.offset=this.ea=this.j=this.o=0;this.updated=!1;this.m=new _ds.Eg}static get observedAttributes(){return["offset","search-active","bottom-row--hidden"]}attributeChangedCallback(a,b,c){switch(a){case "offset":this.offset=Number(this.getAttribute("offset")||"")||0;uW(this);break;case "search-active":aIa(this);break;case "bottom-row--hidden":a=
c!==null,b=this.querySelector("devsite-search input.devsite-search-query"),c=this.querySelector(".devsite-header-billboard-search devsite-search input.devsite-search-query"),b&&c&&(a?b.value=c.value:c.value=b.value),bIa(this,a)}}connectedCallback(){cIa(this);yW(this);wW(this);vW(this);this.ra.observe(this,{childList:!0,subtree:!0});uW(this);const a=_ds.B();this.authUser=_ds.sl(_ds.tl(a.href),"authuser")}disconnectedCallback(){this.eventHandler.removeAll();this.ra.disconnect()}qa(){return this.o+this.j-
this.offset}va(){return this.o+this.j}vd(a){this.m&&this.m.resolve();this.m=new _ds.Eg;this.updated=!1;if(a){AW(this,a,".devsite-header-upper-tabs");AW(this,a,".devsite-collapsible-section");AW(this,a,".devsite-product-name-wrapper");AW(this,a,"devsite-language-selector");AW(this,a,"devsite-shell-activate-button");var b=a.querySelector("devsite-search"),c=this.querySelector("devsite-search");b&&c&&zW(b,c);c=a.querySelector("devsite-user");b=this.querySelector("devsite-user");c&&b&&(zW(c,b),c=_ds.B(),
c=_ds.sl(_ds.tl(c.href),"authuser"),c!==this.authUser&&(this.authUser=c,b.refresh()));_ds.Uj(this,this.querySelector("cloudx-additional-tabs"),a.querySelector("cloudx-additional-tabs"),this.querySelector(".devsite-top-logo-row-middle"));dIa(this,a)}!this.updated&&a&&(_ds.Jk(this),this.appendChild(a));yW(this);xW(this)}async ready(){return this.m.promise}};try{customElements.define("devsite-header",eIa)}catch(a){console.warn("devsite.app.customElement.DevsiteHeader",a)};})(_ds_www);
