(function(_ds){var window=this;var ODa=function(){return(0,_ds.N)('<button class="devsite-book-nav-toggle" aria-haspopup="menu"><span class="material-icons devsite-book-nav-toggle-icon"></span></button>')},PDa=function(){return(0,_ds.N)('<div class="devsite-book-nav-blur"></div>')},QDa=function(a){a=a.oL;a=_ds.pI(new _ds.mt("{NUMBER_OF_MATCHING_DESCENDANTS,plural,=1{{XXX_1} match}other{{XXX_2} matches}}"),{NUMBER_OF_MATCHING_DESCENDANTS:a,XXX_1:_ds.Xv(_ds.Zr(1)),XXX_2:_ds.Xv(_ds.Zr(a))});return(0,_ds.N)('<span class="devsite-nav-filter-match-count"> (<mark>'+
a+"</mark>)</span>")};var RDa="onpointerover"in window?"pointerover":"mouseover",ES=function(a){const b=a.querySelectorAll(".devsite-nav-item").length>0,c=document.querySelector("#devsite-hamburger-menu");c&&(b?c.removeAttribute("visually-hidden"):_ds.Sj(a,"visually-hidden","",c))},SDa=async function(a){a.classList.contains("hide-collapsed-panel")&&a.classList.remove("hide-collapsed-panel");var b=document.documentElement.scrollHeight-document.documentElement.clientHeight;const c=b?document.documentElement.scrollTop/b:
0;a.eventHandler.Kb(a,_ds.fl,()=>{a.removeAttribute("animatable");a.background.removeAttribute("animatable");a.ea.removeAttribute("animatable")});_ds.Sj(a,"animatable","");b=_ds.Ef(a.oa`animatable`);b(a.background,"animatable","");b(a.ea,"animatable","");a.hasAttribute("collapsed")?(_ds.Sj(a,"aria-label","Hide side navigation",a.j),_ds.Sj(a,"data-title","Hide side navigation",a.j),a.removeAttribute("collapsed"),_ds.BL(a.j,"expanded","true"),FS(a,"Expanded book nav")):(_ds.Sj(a,"aria-label","Show side navigation",
a.j),_ds.Sj(a,"data-title","Show side navigation",a.j),_ds.Sj(a,"collapsed",""),_ds.BL(a.j,"expanded","false"),FS(a,"Collapsed book nav"),a.eventHandler.Kb(a,_ds.fl,()=>{a.classList.add("hide-collapsed-panel")}));await _ds.Ml();b=document.documentElement.scrollHeight-document.documentElement.clientHeight;document.documentElement.scrollTop=Math.round(c*b)},UDa=function(a){a.eventHandler.listen(a,"click",b=>void GS(a,b));a.eventHandler.listen(a,"keypress",b=>{b.key==="Enter"&&GS(a,b)});a.eventHandler.listen(a,
[RDa,"focusin"],b=>void TDa(a,b));a.eventHandler.listen(document.body,"devsite-sitemask-hidden",()=>{a.o&&(HS(a,"_book")?a.removeAttribute("top-level-nav"):_ds.Sj(a,"top-level-nav",""))});a.eventHandler.listen(document.body,"devsite-page-loaded",()=>void a.va.fb());a.eventHandler.listen(a,"devsite-content-updated",()=>{a.va.fb()});a.eventHandler.listen(a,"scroll",()=>{_ds.Sj(a,"user-scrolled","")});a.eventHandler.listen(a.j,"click",()=>{a.Ga.fb()});a.m&&(a.eventHandler.listen(a.m,"keyup",()=>void a.ya.fb()),
a.eventHandler.listen(a.m,"focus",()=>void IS(a,"focus")));a.ua&&a.eventHandler.listen(a.ua,["click","keydown"],b=>{if(b.type==="click"||b.key==="Enter"||b.key==="Escape"){a.m&&(a.m.value="",a.m.focus());let c;(c=a.ua)==null||c.classList.add("hidden");JS(a);KS(a);IS(a,b.type)}})},LS=function(a,b=a,c=!0){b=Array.from(b.querySelectorAll(".devsite-nav-title"));a.qa=new Set(b);if(!_ds.B().hash&&c)VDa(a,a.qa);else{c=new _ds.xL;for(const d of a.qa)_ds.wL(c,d)}},MS=async function(a){const b=await _ds.v();
for(const c of a.qa)b.unregisterIntersectionForElement(c)},GS=function(a,b){if(!b.defaultPrevented){var c=b.target;c.getAttribute("id")==="devsite-close-nav"&&(b.preventDefault(),b.stopPropagation(),a.scrollTop=0,a.hasAttribute("top-level-nav")?a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0})):_ds.Sj(a,"top-level-nav",""));if(c.hasAttribute("menu")){var d=c.getAttribute("menu");d&&HS(a,d)&&(b.preventDefault(),b.stopPropagation(),a.scrollTop=0,a.removeAttribute("top-level-nav"))}var e=
c.closest(".devsite-expandable-nav");if(e&&(d=c.closest(".devsite-nav-title, .devsite-nav-toggle"))){let f=b.target,g,h;if(!((g=f)==null?0:(h=g.closest(".devsite-nav-title"))==null?0:h.hasAttribute("href"))){for(b=b.type==="click"||b.type==="touchend";f&&f!==e;){if(f.classList.contains("devsite-nav-title-no-path")&&b){f.blur();break}f=f.parentNode}e.querySelector(".devsite-nav-section")&&(b=e.classList.toggle("expanded"),(e=e.querySelector(".devsite-nav-title"))&&_ds.Sj(a,"aria-expanded",`${b}`,e))}if(d.matches(".devsite-nav-toggle"))return}c.closest(".devsite-nav-title-no-path")||
(a.o&&(d=a.o.querySelector("[menu=_book]"))&&d.contains(c)&&a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0})),(c=c.closest("a.devsite-nav-title"))&&!c.classList.contains("devsite-nav-has-children")&&a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0})))}},TDa=function(a,b){b.defaultPrevented||(b=_ds.bl(b.target,c=>c instanceof HTMLAnchorElement&&c.hasAttribute("href")||c===a,!0),b!==a&&_ds.uf(b,_ds.Gl(b.href).href))},IS=function(a,b){a.dispatchEvent(new CustomEvent("devsite-analytics-observation",
{detail:{category:"Site-Wide Custom Events",action:b,label:b==="focus"?"devsite-book-nav-filter input":"devsite-book-nav-filter filter-clear-button"},bubbles:!0}))},NS=function(a){a.xa=Array.from(a.querySelectorAll(".devsite-mobile-nav-bottom .devsite-nav-list[menu=_book] .devsite-nav-item:not(.devsite-nav-heading)"))},PS=function(a){const b=_ds.B().searchParams.get("nf");a.m&&b&&(a.m.value=b,OS(a))},OS=function(a){if(a.xa.length){JS(a);KS(a);var b,c,d=(b=a.m)==null?void 0:(c=b.value)==null?void 0:
c.trim().toLowerCase();if(d){var e;(e=a.ua)==null||e.classList.remove("hidden");for(const g of a.xa){var f=g.querySelectorAll(".devsite-nav-text");a=g.classList.contains("devsite-nav-expandable");e=c=!1;b=0;let h,k,l;const m=((l=(h=g)==null?void 0:(k=h.getAttribute("data-synonyms"))==null?void 0:k.split(","))!=null?l:[]).some(q=>q.toLowerCase().includes(d));let n,p;if(d&&a&&(m||((n=g.querySelector(".devsite-nav-text"))==null?0:(p=n.textContent)==null?0:p.toLowerCase().includes(d))))e=c=!0;else for(const q of f){let t,
x,C,G;f=((G=(t=q)==null?void 0:(x=t.parentElement)==null?void 0:(C=x.getAttribute("data-synonyms"))==null?void 0:C.split(","))!=null?G:[]).some(I=>I.toLowerCase().includes(d));if(d){let I;if(f||((I=q.textContent)==null?0:I.toLowerCase().includes(d)))c=!0,++b}}if(c===!0){g.classList.remove("hidden");if(e){c=Array.from(g.querySelectorAll(".devsite-nav-item"));for(const q of c){q.classList.remove("hidden");let t,x,C,G;c=((G=(t=q)==null?void 0:(x=t.parentElement)==null?void 0:(C=x.getAttribute("data-synonyms"))==
null?void 0:C.split(","))!=null?G:[]).some(E=>E.toLowerCase().includes(d));let I;d&&(c||((I=q.textContent)==null?0:I.toLowerCase().includes(d)))&&++b}}WDa(g,d)}a&&b>0&&XDa(g,b)}}else(f=a.ua)==null||f.classList.add("hidden")}},JS=function(a){for(const b of a.xa){let c;b.classList.toggle("hidden",!((c=a.m)==null||!c.value))}},KS=function(a){if(a.querySelector("mark")){var b=[...a.querySelectorAll(".devsite-nav-text > .devsite-nav-filter-match-count")];for(const c of b)c.remove();a=[...a.querySelectorAll(".devsite-nav-text > mark")];
for(const c of a){a=c.parentElement;let d;b=(d=a)==null?void 0:d.textContent;a&&b&&_ds.Cf(a,_ds.Zf(b))}}},WDa=function(a,b){if(a=a.querySelector(".devsite-nav-text")){var c,d=(c=a.textContent)==null?void 0:c.replace(new RegExp(`(${b})`,"ig"),"<mark>$1</mark>");d&&_ds.Cf(a,_ds.Zf(d))}},XDa=function(a,b){if(a=a.querySelector(".devsite-nav-text"))b=_ds.dq(QDa,{oL:b}),a.appendChild(b)},VDa=async function(a,b){if(a.connected){var c=await _ds.v(),d=new _ds.xL,e=f=>{f=f.target;_ds.wL(d,f);a.qa.delete(f);
c.unregisterIntersectionForElement(f)};for(const f of b)try{c.registerIntersectionForElement(f,e)}catch(g){e({target:f})}}},HS=function(a,b){let c=!1;if(a.o)for(const d of a.o.querySelectorAll("[menu]"))d.getAttribute("menu")===b?(d.removeAttribute("hidden"),c=!0):_ds.Sj(a,"hidden","",d);return c},QS=function(a,b=a){b||(b=a);for(const c of b.querySelectorAll(".devsite-nav-active"))c.classList.remove("devsite-nav-active"),c.removeAttribute("aria-current");a=_ds.Rl(_ds.B().pathname);a=`[href="${_ds.Gl(a).href}"], [href="${a}"],
        [alt-paths~="${a}"]`;for(const c of b.querySelectorAll(a))c.classList.add("devsite-nav-active"),_ds.BL(c,"current","page")},RS=function(a,b=a){b||(b=a);if(a=b.querySelector(".devsite-mobile-nav-bottom"))for(a=a.querySelector(".devsite-nav-active");a&&a.parentElement&&a.parentElement!==b;)a.matches(".devsite-expandable-nav:not(.expanded)")&&a.classList.add("expanded"),a=a.parentElement},YDa=async function(a){a.connected&&(a.removeAttribute("user-scrolled"),await _ds.Ml(),await SS(a),await a.Ba,
await _ds.v(),await _ds.Ml(),await SS(a))},SS=async function(a){if(a.connected&&a.o){await _ds.v();var b=a.o.querySelector(".devsite-nav-active");b&&(a.hasAttribute("user-scrolled")||await ZDa(a,b))}},ZDa=async function(a,b){if(a.connected){var c=a.hasAttribute("user-scrolled");a.scrollTop=_ds.on(b,a,!0).y;await _ds.Ml();c&&_ds.Sj(a,"user-scrolled","")}},FS=function(a,b){a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:{category:"Site-Wide Custom Events",action:"click",label:b},
bubbles:!0}))},TS=class extends _ds.Vj{static get observedAttributes(){return["collapsed","fixed","hidden"]}constructor(){super();this.connected=!1;this.ua=this.m=this.ra=this.o=null;this.xa=[];this.eventHandler=new _ds.D;this.Aa=()=>{};this.qa=new Set;_ds.Rj(this,this.oa`animatable`,this.oa`aria-expanded`,this.oa`aria-label`,this.oa`collapsed`,this.oa`data-title`,this.oa`fixed`,this.oa`has-book-nav`,this.oa`hidden`,this.oa`top-level-nav`,this.oa`user-scrolled`,this.oa`visually-hidden`);this.background=
document.createElement("div");this.background.classList.add("devsite-book-nav-bg");this.j=_ds.dq(ODa);this.ea=_ds.dq(PDa);this.Ba=new Promise(a=>{this.Aa=a});this.va=new _ds.Og(()=>{this.connected&&ES(this)},20);this.ya=new _ds.Og(()=>{OS(this)},20);this.Ga=new _ds.Og(()=>{SDa(this)},100)}async connectedCallback(){this.connected=!0;_ds.Kk(this.background,this);this.hasAttribute("hidden")&&(_ds.Sj(this,"hidden","",this.j),_ds.Sj(this,"hidden","",this.ea));let a;(a=this.parentElement)==null||a.insertBefore(this.j,
this.nextSibling);_ds.Sj(this,"aria-label","Hide side navigation",this.j);_ds.Sj(this,"data-title","Hide side navigation",this.j);_ds.Sj(this,"aria-expanded","true",this.j);let b;(b=this.parentElement)==null||b.insertBefore(this.ea,this.nextSibling);if(this.ra=this.querySelector(".devsite-book-nav-filter"))this.m=this.ra.querySelector("input[type=text]"),this.ua=this.ra.querySelector(".filter-clear-button"),NS(this),PS(this);ES(this);UDa(this);await this.init();LS(this)}disconnectedCallback(){this.connected=
!1;this.eventHandler.removeAll();MS(this);this.qa.clear();var a=document.querySelector("#devsite-hamburger-menu");a&&_ds.Sj(this,"visually-hidden","",a);a=[this.background,this.j,this.ea];for(const b of a)b&&_ds.Mk(b);this.removeAttribute("animatable");this.background.removeAttribute("animatable");this.ea.removeAttribute("animatable");this.ea.style.removeProperty("--devsite-js-book-nav-scrollbar-width")}attributeChangedCallback(a){a==="hidden"&&this.dispatchEvent(new CustomEvent(this.hasAttribute("hidden")?
"devsite-element-hidden":"devsite-element-visible",{bubbles:!0}));if(a==="hidden"||a==="collapsed"){var b=document.querySelector(".devsite-main-content");b&&(this.hasAttribute("collapsed")||this.hasAttribute("hidden")?b.removeAttribute("has-book-nav"):_ds.Sj(this,"has-book-nav","",b))}if(a==="fixed"||a==="hidden"||a==="collapsed"){b=this.hasAttribute(a);const c=[this.background,this.j,this.ea];for(const d of c)d&&(b?_ds.Sj(this,a,"",d):d.removeAttribute(a))}a==="fixed"&&this.Aa()}async init(a=!0){if(this.connected){this.ea.style.setProperty("--devsite-js-book-nav-scrollbar-width",
`${this.offsetWidth-this.clientWidth}px`);this.o=this.querySelector(".devsite-mobile-nav-bottom");_ds.Sj(this,"top-level-nav","");this.o&&this.o.querySelector("[menu=_book]")&&this.removeAttribute("top-level-nav");this.children.length===0&&_ds.Sj(this,"hidden","");if(this.background)for(const b of["hidden","fixed","animatable"])this.hasAttribute(b)&&_ds.Sj(this,b,"",this.background);!this.hasAttribute("hidden")&&a?(QS(this),RS(this),await YDa(this)):(await _ds.Ml(),await SS(this))}}async vd(a){a?
(a=a.querySelector("nav")||null,QS(this,a),RS(this,a),a&&(await MS(this),this.qa.clear(),LS(this,a,!1)),_ds.Uj(this,this.querySelector("nav"),a)):_ds.Jk(this);NS(this);if(this.m){this.m.value="";let b;(b=this.ua)==null||b.classList.add("hidden");PS(this)}await _ds.Ml();await this.init(!1)}};TS.prototype.updateContent=TS.prototype.vd;TS.prototype.attributeChangedCallback=TS.prototype.attributeChangedCallback;TS.prototype.disconnectedCallback=TS.prototype.disconnectedCallback;
TS.prototype.connectedCallback=TS.prototype.connectedCallback;try{customElements.define("devsite-book-nav",TS)}catch(a){console.warn("Unrecognized DevSite custom element - DevsiteBookNav",a)};})(_ds_www);
